-- -- Your SQL goes here

-- INSERT INTO users (uname,psw_hash,email) VALUES 
-- ('bot','4YABluoxB1sj7BCtUrOpnl','luolongcug@gmail.com');

-- INSERT INTO blogs (aname,blog_link,tw_link,gh_link,is_top) VALUES 
-- ('Nicholas Matsakis',
-- 'http://smallcultfollowing.com/babysteps/',
-- 'https://twitter.com/nikomatsakis',
-- 'https://github.com/nikomatsakis',
-- true),
-- ('Ralf Jung',
-- 'https://www.ralfj.de/blog/',
-- '',
-- 'https://github.com/RalfJung/',
-- true),
-- ('Nick Fitzgerald',
-- 'https://fitzgeraldnick.com/',
-- 'https://twitter.com/fitzgen',
-- 'https://github.com/fitzgen',
-- true),
-- ('Saoirse Shipwreckt',
-- 'https://boats.gitlab.io/blog/',
-- 'https://twitter.com/withoutboats',
-- 'https://github.com/withoutboats',
-- true),
-- ('Nick Cameron',
-- 'https://www.ncameron.org/blog/',
-- 'https://twitter.com/nick_r_cameron',
-- 'https://github.com/nrc',
-- true),
-- ('Steve Klabnik',
-- 'https://words.steveklabnik.com/',
-- 'https://twitter.com/steveklabnik',
-- 'https://github.com/steveklabnik',
-- true);
